### ISSUE TITLE
USE EXPRESS TYPES FOR REQUEST AND RESPONSE 

### ISSUE THREAD

**Issue by SallamAltanna** [MMortaga/Dynmap-Tracker#1]
:stuck_out_tongue_closed_eyes:
https://github.com/MMortaga/Dynmap-Tracker/blob/dfbcfb48d40564f5b11d454616ca7ca0f556d621/src/controllers/homepage.ts#L1

**Comment by MMortaga** [comment]
Good point, would be great if you could create a pull request that fixes this issue.

**Comment by SallamAltanna** [comment]
@MMortaga DO NOT USE EXPRESS TYPES FOR REQUEST AND RESPONSE

**Comment by MMortaga** [comment]
@sallamTanna Please include this in your pull request
